// === WEBSITE LAYOUT ===
// import { ReactNode } from 'react';
import {NextIntlClientProvider, hasLocale} from 'next-intl';
import ReactQueryProvider from '@/app/providers/ReactQueryProvider';
import {notFound} from 'next/navigation';
import { routing } from '../../../../i18n/routing';
// import { Rubik } from "next/font/google";
import type { Metadata } from "next";
import "../../../globals.css";
import app_identity from '@/app/config/identity';
import WhatsAppButton from '@/app/components/global/WhatsAppButton/WhatsAppButton';

// const rubikSans = Rubik({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "LAEQ365",
  description: "Generated by LAEQ",
  keywords:"",
};

import Nave from '@/app/components/website/Nave/Nave';
import Footer from '@/app/components/website/Footer/Footer';


// interface LayoutProps {
//   children: ReactNode;
// }

export default async function WebsiteLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}) {
  // Ensure that the incoming `locale` is valid
  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  let messages;
  try {
    messages = (await import(`@/locales/${locale}.json`)).default;
  } catch (error) {
    console.log(error)
    notFound(); // في حالة عدم العثور على ملف الترجمة
  }
  
  const current_year = new Date().getFullYear()
 
  return (
    <div style={{fontFamily:app_identity.primary_font}}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ReactQueryProvider>
            <Nave/>
            <WhatsAppButton phone='+966570000102' message='Hi IN LAEEQ356 APP'/>
            {children}
            <Footer/>
          </ReactQueryProvider>
        </NextIntlClientProvider>
        <div style={{borderTop:'1px #323135 solid', opacity:'10%'}}></div>
            <p style={{color:"#32313580",height:'50px',padding:'10px 5px',textAlign:'center'}}>© {current_year} All Rights Reserved</p>
    </div>
  );
}