const CategoriesList = [
  "Conventional ovens",
  "Convection ovens",
  "Pizza ovens",
  "Combi ovens",
  "Gas ranges",
  "Electric ranges",
  "Induction cooktops",
  "Deep fryers",
  "Countertop fryers",
  "Charbroilers",
  "Flat-top griddles",
  "Panini presses",
  "Commercial steamers",
  "Microwave steamers",
  "Reach-in refrigerators",
  "Walk-in refrigerators",
  "Undercounter refrigerators",
  "Reach-in freezers",
  "Walk-in freezers",
  "Chest freezers",
  "Food Preparation Equipment",
  "Stand mixers",
  "Hand mixers",
  "Food Processors",
  "Slicers",
  "Blenders",
  "Mandolins",
  "Chopping Boards and Knives",
  "Cleaning and Sanitation",
  "Commercial dishwashers",
  "Glass washers",
  "Three-compartment sinks",
  "Handwashing sinks",
  "Waste disposal units",
  "Trash cans",
  "Recycling bins",
  "Compost bins",
  "Dining Area Equipment",
  "Furniture",
  "Dining tables",
  "High-top tables",
  "Buffet tables",
  "Dining chairs",
  "Bar stools",
  "Booths",
  "Serving trays",
  "Chafing dishes",
  "Condiment dispensers",
  "Water pitchers",
  "Beverage dispensers",
  "Espresso machines",
  "Drip coffee makers",
  "Plates",
  "Glassware",
  "Cutlery",
  "Tablecloths and napkins",
  "Centerpieces",
  "Menus and menu boards",
  "Additional Equipment",
  "Temperature sensors",
  "Humidity sensors",
  "Motion sensors for lighting",
  "For monitoring humidity levels in storage areas",
  "Spatulas",
  "Tongs",
  "Whisks",
  "Rolling pins",
  "Baking sheets",
  "Digital food thermometers",
  "Infrared thermometers",
  "Probe thermometers",
  "Exhaust hoods",
  "Make-up air units",
  "Fire Suppression Systems",
  "Shelving units",
  "Food storage containers",
  "Other",
].map((value, index) => ({
  id: index + 1,
  value,
}));

export default CategoriesList;
